services:
  - type: web
    name: glowr-api
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 5000
      - key: NODE_ENV
        value: production
      - fromGroup: glowr-env # Plan to create this group in Render dashboard
